services:
  db_api:
    build: containers/db_api
    links:
      - "database"
    ports:
      - "8000:5000"
  database:
    build: containers/db
# Uncomment to expose the database on the host machine
#    ports:
#      - "5432:5432"
